version: '3.4'

name: sdpsic-api-project
services: 
  smartdigitalpsicowebapi: 
    image: sdp_api_cloud_image_v2
    container_name: sdp_api_container
    build:
      context: .
      dockerfile: SmartDigitalPsico.WebAPI/Dockerfile 
    ports:   
       - "80:80"  
       - "443:443"   