version: '3.4'

name: sdpsic-api-project
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 3320:3326
  dbSQLSERVER:
    image: mcr.microsoft.com/mssql/server:latest    
    restart: always   
    container_name: smartdigitalpsicoSQLServer
    environment: 
      TZ: America/Sao_Paulo
      ACCEPT_EULA:  "Y"       
      SA_PASSWORD: docker!123 
    ports:
      - 1433:1433
    networks:
      - smartdigitalpsiconetwork
  smartdigitalpsicowebapi:
    image: sdpapiimage
    container_name: sdpapicontainer
    build:
      context: .
      dockerfile: SmartDigitalPsico.WebAPI/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports: # porta do host:porta do container.
       - 80:80 
       - 443:443 
       - 5001:5001 
    links:
      - dbSQLSERVER
    depends_on:
      - dbSQLSERVER 
    networks:
      - smartdigitalpsiconetwork
#  client: 
#    build:
#      context: ./SmartDigitalPsico.UI.DashBoard
#      dockerfile: Dockerfile
#    ports:
#      - "4209:4209"
#    restart: always
#    volumes:
#      - ./SmartDigitalPsico.UI.DashBoard/dist/smartdigitalpsico/:/usr/share/nginx/html
#    command: nginx -g 'daemon off;'
#    links:
#      - smartdigitalpsico.webapi
#    depends_on:
#      - smartdigitalpsico.webapi 
#    networks:
#      - smartdigitalpsiconetwork 
networks:
  smartdigitalpsiconetwork:
    driver: bridge