version: '3.4'

name: sdpsic-api-project
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 3320:3326
  dbSQLSERVER:
    image: mcr.microsoft.com/mssql/server:latest    
    restart: always   
    container_name: smartdigitalpsicoSQLServer
    environment: 
      TZ: America/Sao_Paulo
      ACCEPT_EULA:  "Y"       
      SA_PASSWORD: docker!123 #sa / #sdpdbauser
    ports:
      - 1433:1433
    networks:
      - smartdigitalpsiconetwork
  smartdigitalpsicowebapi:
    #image: leonecr/sdpapiimage:latest #sdpapi-image
    image: sdpapi-image
    container_name: sdpapicontainer
    build:
      context: .
      dockerfile: SmartDigitalPsico.WebAPI/Dockerfile 
    ports:  
       #- "80" 
       #- "443"    
       - 80:80  
       - 443:443  
    links:
      - dbSQLSERVER
    depends_on:
      - dbSQLSERVER 
    networks:
      - smartdigitalpsiconetwork 
  dashui:  
     image:  sdpuidash-image
     container_name:  sdpuidashcontainer
     build:
       context: ./SmartDigitalPsico.UI.DashBoard
       dockerfile: Dockerfile
     ports:  
       - "4209:4209"
     restart: always
     volumes:
       - ./SmartDigitalPsico.UI.DashBoard/dist/smartdigitalpsico/:/usr/share/nginx/html
     command: nginx -g 'daemon off;'
     links:
       - smartdigitalpsicowebapi
     depends_on:
       - smartdigitalpsicowebapi 
     networks:
       - smartdigitalpsiconetwork 
networks:
  smartdigitalpsiconetwork:
    driver: bridge