version: '3.4'

name: sdpsic-api-project
services:   
  dashui: 
     #image: leonecr/sdpuidashimage:latest #sdpuidash-image
     image:  sdpuidash-image
     container_name:  sdpuidashcontainer
     build:
       context: ../SmartDigitalPsico.UI.DashBoard
       dockerfile: Dockerfile
     ports:
       - "80:80"
       - "8080:8080"
       - "4209:4209"
     restart: always
     volumes:
       - ./SmartDigitalPsico.UI.DashBoard/dist/smartdigitalpsico/:/usr/share/nginx/html
     command: nginx -g 'daemon off;' 
     networks:
       - smartdigitalpsiconetwork 
networks:
  smartdigitalpsiconetwork:
    driver: bridge