version: '3.4'

name: sdpsic-api-project
services:  
  smartdigitalpsicowebapi:
    #image: leonecr/sdpapiimage:latest #sdpapi-image
    image: sdpapi-imagecloud
    container_name: sdpapicontainer
    build:
      context: .
      dockerfile: SmartDigitalPsico.WebAPI/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production 
      ASPNETCORE_URLS: https://+:443;http://+:80
    ports: # porta do host:porta do container    
       - 80:80  
       - 443:443  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro    
